### ISSUE TITLE
Copying file into initramfs fails

### ISSUE THREAD

**Issue by narodnik** [desultory/ugrd#20]
I'm trying to copy a file into the initramfs to make it available for the key_file argument of cryptsetup.

```toml
[copies.key]
source = "/boot/volume.key"
destination = "/boot/volume.key"
```
complains that `AttributeError: 'str' has no attribute 'parent'`, looking at the line in the backtrace:

```py
            self.logger.debug("Parent directory for '%s' does not exist: %s" % (dest_path.name, dest.parent))
```

Seems like a bug since dest is of type str.
